export const MICROSOFT_365_FEATURE_KEYS = {
  WEB_MOBILE_OFFICE: 'WEB_MOBILE_OFFICE',
  DESKTOP_OFFICE: 'DESKTOP_OFFICE',
  BUSINESS_EMAIL: 'BUSINESS_EMAIL',
  ONEDRIVE_1TB: 'ONEDRIVE_1TB',
  TEAMS: 'TEAMS',
} as const;

export type Microsoft365FeatureKey = typeof MICROSOFT_365_FEATURE_KEYS[keyof typeof MICROSOFT_365_FEATURE_KEYS];

export const MICROSOFT_365_PLAN_CODES = {
  BUSINESS_BASIC: 'BUSINESS_BASIC',
  BUSINESS_STANDARD: 'BUSINESS_STANDARD',
} as const;

export type Microsoft365PlanCode = typeof MICROSOFT_365_PLAN_CODES[keyof typeof MICROSOFT_365_PLAN_CODES];
